name: PmChair
main: maru.PmChair
author: maru, PetteriM1
version: "${pom.version}"
api: ["1.1.0"]

commands:
  chair:
    usage: "/chair <on|off>"
    description: "Enable/disable chairs"
    permission: "chair.toggle"

permissions:
  chair.toggle:
    default: true
    description: "Enable/disable chairs"
